st_name=input("Enter student's name: ")
st_roll=int(input("Enter student's roll number: "))
st_class=input("Enter student's class: ")
college=input("Enter student's college name: ")
fee=int(input("Enter college fee: "))
address=input("Enter student's address: ")
print("Student's name :",st_name)
print("Roll number :",st_roll)
print("Class :" ,st_class)
print("College :",college)
print("College Fee: ",fee)
print("Student's Address: ",address)